# Generated by Django 4.2.2 on 2023-10-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_subscriber_currency_subscription_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='depart_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='flight_max_duration_in_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='flight_max_stops',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trip_duration_in_days_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trip_duration_in_days_min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
