# Generated by Django 4.2.2 on 2023-11-02 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_subscription_destination_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationcoordinate',
            name='airport',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
