# Generated by Django 4.2.2 on 2023-11-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_destinationcoordinate_airport'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='exact_dates',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
