# Generated by Django 4.2.2 on 2023-11-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_subscription_exact_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinationcoordinate',
            name='airport',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='exact_dates',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
