# Generated by Django 4.2.2 on 2023-11-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_destinationcoordinate_airport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='vip',
            field=models.BooleanField(default=False),
        ),
    ]
