# Generated by Django 4.2.2 on 2023-11-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_subscription_vip'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
