# Generated by Django 4.2.2 on 2023-11-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_subscription_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subscribers',
            field=models.ManyToManyField(related_name='subscribers', to='app.subscriber'),
        ),
    ]
