# Generated by Django 4.2.2 on 2023-11-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_subscription_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscribers',
            field=models.ManyToManyField(related_name='subscriptions', to='app.subscriber'),
        ),
    ]
