# Generated by Django 4.2.2 on 2023-11-18 17:19

from django.db import migrations

def make_many_subscribers(apps, schema_editor):
    """
        Adds the Author object in Book.author to the
        many-to-many relationship in Book.authors
    """
    Subscription = apps.get_model('app', 'Subscription')

    for subscription in Subscription.objects.all():
        subscription.subscribers.add(subscription.subscriber)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_subscription_subscribers'),
    ]

    operations = [
        migrations.RunPython(make_many_subscribers),
    ]
