# Generated by Django 4.2.2 on 2023-11-18 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_subscriber_subscriptions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='subscriber',
            new_name='subscriber_old',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='subscriptions',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='subscribers',
        ),
    ]
