# Generated by Django 4.2.2 on 2023-11-18 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_subscriber_subscription_subscriber_old_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscriber_old',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_old', to='app.subscriber'),
        ),
        migrations.CreateModel(
            name='SubscriptionsToSubscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subscriber')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subscription')),
            ],
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscribers',
            field=models.ManyToManyField(blank=True, through='app.SubscriptionsToSubscribers', to='app.subscriber'),
        ),
    ]
