# Generated by Django 4.2.2 on 2023-11-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_subscription_subscriber_old_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, through='app.SubscriptionsToSubscribers', to='app.subscription'),
        ),
    ]
