# Generated by Django 4.2.2 on 2023-12-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_subscription_subscriber_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
