# Generated by Django 4.2.2 on 2024-01-08 01:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0021_flighttotrack_monthlyhistoric"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="trip_duration_in_days_max",
            field=models.IntegerField(blank=True, default=14, null=True),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="trip_duration_in_days_min",
            field=models.IntegerField(blank=True, default=7, null=True),
        ),
    ]
