# Generated by Django 4.2.2 on 2024-01-09 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_subscription_trip_duration_in_days_max_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='flighttotrack',
            constraint=models.UniqueConstraint(fields=('depart', 'destination'), name='deparT_destination_unique_constraint'),
        ),
    ]
