# Generated by Django 4.2.2 on 2024-01-11 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_flighttotrack_depart_destination_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='subscribe_to_generic_deals',
            field=models.BooleanField(default=False),
        ),
    ]
