# Generated by Django 4.2.2 on 2024-01-18 02:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0024_subscriber_subscribe_to_generic_deals"),
    ]

    operations = [
        migrations.CreateModel(
            name="DealsReporting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deals_json", models.JSONField()),
            ],
        ),
    ]
