# Generated by Django 4.2.2 on 2024-01-29 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_featureflag_featureflag_name_user_unique_constraint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='destination_coordinate',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='destination_type',
            field=models.CharField(choices=[('AIRPORT', 'Airport'), ('FREE_TEXT', 'Free text search'), ('COUNTRY', 'Country')], default='FREE_TEXT'),
        ),
    ]
