# Generated by Django 4.2.2 on 2024-01-29 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_delete_destinationcoordinate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featureflag',
            old_name='value',
            new_name='enabled',
        ),
    ]
