# Generated by Django 4.2.2 on 2024-02-07 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_rename_value_featureflag_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationToTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_airport_code', models.CharField(help_text='The code of the origin airport', max_length=5)),
                ('destination_country', models.CharField(max_length=50)),
                ('destination_country_code', models.CharField(help_text='This country code will be used by the code', max_length=5)),
            ],
        ),
        migrations.RenameField(
            model_name='monthlyhistoric',
            old_name='average',
            new_name='average_price',
        ),
        migrations.RenameField(
            model_name='monthlyhistoric',
            old_name='maximum',
            new_name='maximum_price',
        ),
        migrations.RenameField(
            model_name='monthlyhistoric',
            old_name='minimum',
            new_name='minimum_price',
        ),
        migrations.AddField(
            model_name='monthlyhistoric',
            name='depart_country_code',
            field=models.CharField(default='NONE', max_length=5),
        ),
        migrations.AddField(
            model_name='monthlyhistoric',
            name='destination_country_code',
            field=models.CharField(default='NONE', max_length=5),
        ),
        migrations.AddConstraint(
            model_name='destinationtotrack',
            constraint=models.UniqueConstraint(fields=('origin_airport_code', 'destination_country_code'), name='airport_country_unique_constraint'),
        ),
    ]
