# Generated by Django 4.2.2 on 2023-11-18 17:19

from django.db import migrations

from app.repositories.airport_repository import AirportRepository
from app.repositories.country_repository import CountryRepository


def populate_country_code_on_historic_metric(apps, schema_editor):
    airport_repository = AirportRepository()
    country_repository = CountryRepository()

    MonthlyHistoric = apps.get_model('app', 'MonthlyHistoric')

    for monthly_historic in MonthlyHistoric.objects.all():
        depart_airport = airport_repository.get_by_code(monthly_historic.depart_airport)
        depart_country = country_repository.get_by_code(depart_airport.country_code)

        destination_airport = airport_repository.get_by_code(monthly_historic.destination_airport)
        destination_country = country_repository.get_by_code(destination_airport.country_code)

        monthly_historic.depart_country_code = depart_country.code
        monthly_historic.destination_code = destination_country.code
        monthly_historic.save()


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0030_destinationtotrack_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_country_code_on_historic_metric),
    ]
