# Generated by Django 4.2.2 on 2024-02-07 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_populate_country_code_on_historic_metric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyhistoric',
            name='depart_country_code',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='monthlyhistoric',
            name='destination_country_code',
            field=models.CharField(max_length=5),
        ),
    ]
