# Generated by Django 4.2.2 on 2024-02-07 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_monthlyhistoric_depart_country_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyhistoric',
            name='number_of_datapoints',
            field=models.BigIntegerField(default=0),
        ),
    ]
