# Generated by Django 4.2.2 on 2024-02-09 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_airport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airport',
            old_name='airport_code_iaco',
            new_name='airport_code_icao',
        ),
        migrations.RemoveField(
            model_name='airport',
            name='country_name',
        ),
    ]
