# Generated by Django 4.2.2 on 2024-02-09 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_rename_airport_code_iaco_airport_airport_code_icao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='airport_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='airport',
            name='region_name',
            field=models.CharField(max_length=100),
        ),
    ]
