# Generated by Django 4.2.2 on 2023-11-18 17:19
import csv
import os

from django.db import migrations


def populate_airport(apps, schema_editor):
    Airport = apps.get_model('app', 'Airport')
    csv_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), "repositories", "iata-icao.csv")
    with open(csv_path, 'r', encoding="utf8") as the_file:
        csv_reader = csv.DictReader(the_file)
        for row in csv_reader:
            Airport.objects.create(
                airport_name=row['airport'],
                airport_code=row['iata'],
                airport_code_icao=row['icao'],
                country_code=row['country_code'],
                region_name=row['region_name'],
                latitude=row['latitude'],
                longitude=row['longitude']
            )


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0036_alter_airport_airport_name_alter_airport_region_name'),
    ]

    operations = [
        migrations.RunPython(populate_airport),
    ]
