# Generated by Django 4.2.2 on 2024-02-14 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_populate_airports'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent_name', models.CharField(max_length=50)),
                ('continent_code', models.CharField(max_length=5)),
                ('country_name', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=5, unique=True)),
            ],
        ),
    ]
