# Generated by Django 4.2.2 on 2023-11-18 17:19
import csv
import os

from django.db import migrations


def populate_country(apps, schema_editor):
    Country = apps.get_model('app', 'Country')
    csv_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), "repositories", "countries.csv")
    with open(csv_path, 'r', encoding="utf8") as the_file:
        csv_reader = csv.DictReader(the_file)
        for row in csv_reader:
            Country.objects.create(
                continent_name=row['continent'],
                continent_code=row['continent_code'],
                country_name=row['country'],
                country_code=row['iso2'],
            )


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0038_country'),
    ]

    operations = [
        migrations.RunPython(populate_country),
    ]
