# Generated by Django 4.2.2 on 2024-02-15 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_populate_countries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destinationtotrack',
            old_name='destination_country_code',
            new_name='destination_code',
        ),
        migrations.RenameField(
            model_name='destinationtotrack',
            old_name='destination_country',
            new_name='destination_name',
        ),
        migrations.AddField(
            model_name='destinationtotrack',
            name='destination_type',
            field=models.CharField(choices=[('AIRPORT', 'Airport'), ('COUNTRY', 'Country')], default='COUNTRY'),
        ),
    ]
