# Generated by Django 4.2.2 on 2024-02-15 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_rename_destination_country_code_destinationtotrack_destination_code_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='destinationtotrack',
            name='airport_country_unique_constraint',
        ),
        migrations.AddConstraint(
            model_name='destinationtotrack',
            constraint=models.UniqueConstraint(fields=('origin_airport_code', 'destination_code', 'destination_type'), name='airport_country_unique_constraint'),
        ),
    ]
