# Generated by Django 4.2.2 on 2024-02-15 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_remove_destinationtotrack_airport_country_unique_constraint_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlightToTrack',
        ),
        migrations.AlterField(
            model_name='destinationtotrack',
            name='destination_code',
            field=models.CharField(help_text='This destination code will be used to identify the destination.', max_length=5),
        ),
        migrations.AlterField(
            model_name='destinationtotrack',
            name='destination_name',
            field=models.CharField(help_text='A descriptive name of the destination. Could later be used to infer the destination code.', max_length=50),
        ),
        migrations.AlterField(
            model_name='destinationtotrack',
            name='origin_airport_code',
            field=models.CharField(default='YUL', help_text='The code of the origin airport', max_length=5),
        ),
    ]
