# Generated by Django 4.2.2 on 2024-02-19 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_delete_flighttotrack_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationtotrack',
            name='destination_airport_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.airport'),
        ),
        migrations.AddField(
            model_name='destinationtotrack',
            name='destination_country_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.country'),
        ),
    ]
