# Generated by Django 4.2.2 on 2024-02-19 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_destinationtotrack_destination_airport_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destinationtotrack',
            old_name='destination_airport_code',
            new_name='destination_airport',
        ),
        migrations.RenameField(
            model_name='destinationtotrack',
            old_name='destination_country_code',
            new_name='destination_country',
        ),
    ]
