# Generated by Django 4.2.2 on 2024-02-19 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_rename_destination_airport_code_destinationtotrack_destination_airport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationtotrack',
            name='origin_airport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_to_track_origin_airport', to='app.airport'),
        ),
    ]
