# Generated by Django 4.2.2 on 2024-02-19 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_populate_destination_to_track_fk'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='destinationtotrack',
            name='airport_country_unique_constraint',
        ),
        migrations.RemoveField(
            model_name='destinationtotrack',
            name='destination_code',
        ),
        migrations.RemoveField(
            model_name='destinationtotrack',
            name='destination_name',
        ),
        migrations.RemoveField(
            model_name='destinationtotrack',
            name='destination_type',
        ),
        migrations.RemoveField(
            model_name='destinationtotrack',
            name='origin_airport_code',
        ),
        migrations.AlterField(
            model_name='destinationtotrack',
            name='origin_airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_to_track_origin_airport', to='app.airport'),
        ),
        migrations.AddConstraint(
            model_name='destinationtotrack',
            constraint=models.UniqueConstraint(fields=('origin_airport', 'destination_airport', 'destination_country'), name='airport_country_unique_constraint'),
        ),
    ]
