# Generated by Django 4.2.2 on 2024-02-19 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_remove_destinationtotrack_airport_country_unique_constraint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='destination_airport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.airport'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='destination_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.country'),
        ),
    ]
