name: Refresh Monthly Historical Data

on:
  workflow_dispatch: {}
  schedule:
    # Every month
    - cron: "0 0 1 * *"

env:
  PGHOST: ${{ secrets.PGHOST }}
  PGUSER: ${{ secrets.PGUSER }}
  PGPASSWORD: ${{ secrets.PGPASSWORD }}
  EMAILUSER: ${{ secrets.EMAILUSER }}
  EMAILPASSWORD: ${{ secrets.EMAILPASSWORD }}
  OPEN_CAGE_API_KEY: ${{ secrets.OPEN_CAGE_API_KEY }}
  KIWI_SEARCH_API_KEY: ${{ secrets.KIWI_SEARCH_API_KEY }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run Scan
        run: |
          python manage.py refresh_monthly_historics
